server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /logs {
        proxy_pass http://backend:5000/logs;
        proxy_set_header Host $host;
    }

    location /stats {
        proxy_pass http://backend:5000/stats;
        proxy_set_header Host $host;
    }

    location /health {
        proxy_pass http://backend:5000/health;
        proxy_set_header Host $host;
    }

    server_tokens off;
}